/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kehwin_recorder_utils_AudioUtils */

#ifndef _Included_com_kehwin_recorder_utils_AudioUtils
#define _Included_com_kehwin_recorder_utils_AudioUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef com_kehwin_recorder_utils_AudioUtils_TARGET_SAMPLER_RATE
#define com_kehwin_recorder_utils_AudioUtils_TARGET_SAMPLER_RATE 16000L
#undef com_kehwin_recorder_utils_AudioUtils_TARGET_BIT_WIDHT
#define com_kehwin_recorder_utils_AudioUtils_TARGET_BIT_WIDHT 16L
#undef com_kehwin_recorder_utils_AudioUtils_TARGET_CHANNEL
#define com_kehwin_recorder_utils_AudioUtils_TARGET_CHANNEL 1L
/*
 * Class:     com_kehwin_recorder_utils_AudioUtils
 * Method:    resampler
 * Signature: ([BII[BII)V
 */
JNIEXPORT void JNICALL Java_com_kehwin_recorder_utils_AudioUtils_resampler
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_kehwin_recorder_utils_AudioUtils
 * Method:    doubleChannel2SingleChannel
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_kehwin_recorder_utils_AudioUtils_doubleChannel2SingleChannel
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     com_kehwin_recorder_utils_AudioUtils
 * Method:    bitWidthConvert
 * Signature: ([BIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_kehwin_recorder_utils_AudioUtils_bitWidthConvert
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint);

/*
 * Class:     com_kehwin_recorder_utils_AudioUtils
 * Method:    byteArray2SamplerArray
 * Signature: ([BI)[I
 */
JNIEXPORT jintArray JNICALL Java_com_kehwin_recorder_utils_AudioUtils_byteArray2SamplerArray
  (JNIEnv *, jclass, jbyteArray, jint,jint);

#ifdef __cplusplus
}
#endif
#endif
